---
version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - PORT=4000
      - BINDING=0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match should match what your application expects. In this case, the
      # compose file is in a sub-folder, so we will mount '..'. We'll then reference this
      # as the workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ../app:/app:cached

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - "database:/var/lib/postgresql/data"

volumes:
  database:
